function [Hmain,dbNIRS] = NewNIRSstudy(Hmain,dbNIRS)
	StudyFigure = figure('Visible', 'on', ...
	'position', Hmain.screenSize./2,...
    'Resize', 'on',...
    'Name', 'New NIRS study', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL');

	
	


end

