function StudyFigure = NewNIRSStudy(~, ~, Hmain,~)

	StudyFigure.MainFigure = figure('Visible', 'on', ...
	'position', Hmain.screenSize.*(1/4),...
    'Resize', 'on',...
    'Name', 'New NIRS Study', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
	);
	
	StudyFigure.Subject.StudyName = uiw.widget.EditableText(...      
    'Parent',StudyFigure.MainFigure,...=
    'Value','Insert Name',...
    'Callback',@(h,e)disp(e),...
    'Label','Study Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.70 0.7 0.25]);
	
	StudyFigure.StudySelector = uiw.widget.FileSelector(...
    'Parent', StudyFigure.MainFigure, ...
    'Value', '/home/pagno/Desktop/dati/demodata.txt', ...
    'Pattern', {'*.mat','MATLAB MAT files (*.mat)'; '*.csv','CSV files (*.csv)'; '*.txt','TXT files (*.txt)'}, ...
    'Callback',@(h,e)disp(e),...
    'Label','Choose a data file:', ...
    'LabelLocation','top',...
    'LabelWidth',150,...
    'Units', 'normalize', ...
    'Position', [0.05 0.35 0.8 0.25]);


	 StudyFigure.SaveButton = uicontrol('Style', 'pushbutton',...
	'String', 'Save',...
	'Units', 'normalize', ...
	'Position', [0.8 0.05 0.2 0.1],...
	'Callback', {@SaveDatatoNewMeasureGUI ,StudyFigure});    

	StudyFigure.LoadButton = uicontrol('Style', 'pushbutton',...
	'String', 'Load',...
	'Units', 'normalize', ...
	'Position', [0.8 0.15 0.2 0.1],...
	'Callback', {@LoadDatatoNewMeasureGUI ,StudyFigure}); 



	StudyFigure.MainFigure.Visible = 'on';

end