function Hmain = NIRSDisplayMeasure(Hmain,dbNIRS)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
	Hmain.DisplayMeasure.Pannel = uipanel (...
		'Title', 'Measure', ...
		'Parent', Hmain.mainFigure,...
		'Units', 'normalized',...
		'Position',[0.21 0.01 0.78 0.88]);
	

end

