function Hmain = NIRSDisplayStudy(Hmain,dbNIRS);
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
	Hmain.DisplayStudy.Pannel = uipanel (...
		'Title', 'Study', ...
		'Parent', Hmain.mainFigure,...
		'Units', 'normalized',...
		'Position',[0.21 0.01 0.78 0.88]);
	
		Hmain.DisplayStudy.TextBoxID = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','ID:',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.85 0.3 0.15]);
		
	
		Hmain.DisplayStudy.TextBoxDate = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Date:',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.75 0.3 0.15]);
		
		
		Hmain.DisplayStudy.TextBoxName = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Name:',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.65 0.3 0.15]);
		
		
		
		Hmain.DisplayStudy.TextBoxEditableName = uiw.widget.EditableText(...      %%questo e' quello editabile
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','Insert Name',...
			'Callback',@(h,e)disp(e),...
			'Label','Name:',...
			'LabelLocation','left',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.65 0.3 0.15],...
			'Visible', 'off');
		
		
		
		
		Hmain.DisplayStudy.TextBoxNumbMeasure = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','N. Measure:',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.55 0.3 0.15]);
		
		
		
		Hmain.DisplayStudy.TextBoxFirstMeasure = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Date First Measure',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.45 0.3 0.15]);
		
		Hmain.DisplayStudy.TextBoxLastMeasure = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Date Last Measure',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.05 0.35 0.3 0.15]);

		
		Hmain.DisplayStudy.TextBoxNote = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Note:',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.55 0.85 0.3 0.15]);
		
		
		Hmain.DisplayStudy.TextBoxEditableNote = uiw.widget.EditableText(...      %%questo e' quello editabile
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','Insert Note',...
			'Callback',@(h,e)disp(e),...
			'Label','Note:',...
			'LabelLocation','left',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.55 0.85 0.3 0.15],...
			'Visible', 'off');
		
		
		Hmain.DisplayStudy.TextBoxNumbGroupA = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','N. Group Analysis:',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.55 0.75 0.3 0.15]);
		
		
		
		Hmain.DisplayStudy.TextBoxFirstGroupA = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Date First Group Analysis',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.55 0.65 0.3 0.15]);
		
		Hmain.DisplayStudy.TextBoxLastGroupA = uiw.widget.FixedText(...      
			'Parent',Hmain.DisplayStudy.Pannel,...=
			'Value','',...
			'Label','Date Last Group Analysis',...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[0.55 0.55 0.3 0.15]);
		
		
		Hmain.DisplayStudy.ToggleButton = uicontrol('Style', 'togglebutton',...
			'String', 'Edit',...
			'Parent',Hmain.DisplayStudy.Pannel,...
			'Units','normalized',...
			'Position', [0.20 0.20 0.1 0.04],...
			'Callback', {@Edit_Field,Hmain.DisplayStudy});  
	

end



function Edit_Field(PushHandle,~,MainHandle)


	if PushHandle.Value == 1
			set(MainHandle.TextBoxEditableName,'Visible', 'on');
			set(MainHandle.TextBoxEditableNote,'Visible', 'on');
			set(MainHandle.TextBoxName,'Visible', 'off');
			set(MainHandle.TextBoxNote,'Visible', 'off');
	else
			set(MainHandle.TextBoxEditableName,'Visible', 'off');
			set(MainHandle.TextBoxEditableNote,'Visible', 'off');
			set(MainHandle.TextBoxName,'Visible', 'on');
			set(MainHandle.TextBoxNote,'Visible', 'on');
	end
	
	
end















