function [StudyFigure,dbNIRS] = NewNIRSMeasure(objHandle, ~ ,Hmain,dbNIRS)
	
	set(objHandle, 'Enable', 'off')
	drawnow;


StudyFigure.MainFigure = figure(...
	'position', Hmain.screenSize.*(3/4),...MainHandle
    'Resize', 'on',...
    'Name', 'New NIRS measure', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'DeleteFcn', {@renableHandle,objHandle},...
	'Visible', 'off' ...
);

%% Editable text for subject
	
StudyFigure.Subject.Pannel = uipanel (...
		'Title', 'Subject', ...
		'parent', StudyFigure.MainFigure,...
		'Units', 'normalized',...
		'Position',[0.01 0.39 0.45 0.6]);
	
	
 % inserire controllo data nascita 
	%name
	StudyFigure.Subject.Name = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Subject.Pannel,...=
    'Value','Insert Name',...
    'Callback',@(h,e)disp(e),...
    'Label','Name:',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.85 0.7 0.08]);
	
	%surname
	StudyFigure.Subject.Surname = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Subject.Pannel,...=
    'Value','Insert Surname',...
    'Callback',@(h,e)disp(e),...
    'Label','Surname:',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.65 0.7 0.08]);

	StudyFigure.Subject.BirthDate = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Subject.Pannel,...=
    'Value','31/05/2018',...
    'Callback',@(h,e)disp(e),...
    'Label','Birthdate:',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.65 0.7 0.08]);

	%Apgar1
	StudyFigure.Subject.Apgar1 = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Subject.Pannel,...=
    'Value','Insert Apgar1',...
    'Callback',@(h,e)disp(e),...
    'Label','Apgar1:',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.45 0.7 0.08]);

	%Apgar5
	StudyFigure.Subject.Apgar5 = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Subject.Pannel,...=
    'Value','Insert Apgar5',...
    'Callback',@(h,e)disp(e),...
    'Label','Apgar5:',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.25 0.7 0.08]);

	%note
	StudyFigure.Subject.Note = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Subject.Pannel,...=
    'Value','',...
    'Callback',@(h,e)disp(e),...
    'Label','Note:',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Units','normalized',...
	'IsMultiLine', true,...
    'Position',[0.05 0.05 0.7 0.08]);

%% Text for Measure (imported)
	StudyFigure.Measure.Pannel = uipanel (...
		'Title', 'Measure', ...
		'parent', StudyFigure.MainFigure,...
		'Units', 'normalized',...
		'Position',[0.5 0.39 0.49 0.6]);
		
	%Date
	StudyFigure.Measure.Date = uiw.widget.FixedText(...      
    'Parent',StudyFigure.Measure.Pannel,...=
    'Value','',...
    'Label','Date:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.85 0.3 0.15]);
	
	%Length
	StudyFigure.Measure.Length = uiw.widget.FixedText(...      
    'Parent',StudyFigure.Measure.Pannel,...=
    'Value','',...
    'Label','Length:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.65 0.3 0.15]);

	%DetectorCH
	StudyFigure.Measure.DetectorCH = uiw.widget.FixedText(...      
    'Parent',StudyFigure.Measure.Pannel,...=
    'Value','',...
    'Label','N. Detector CH.',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.45 0.3 0.15]);

	%AnalogCH
	StudyFigure.Measure.AnalogCH = uiw.widget.FixedText(...      
    'Parent',StudyFigure.Measure.Pannel,...=
    'Value','',...
    'Label','N. Detector CH.',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.25 0.3 0.15]);

	%noteMainHandle
	StudyFigure.Measure.note = uiw.widget.EditableText(...      
    'Parent',StudyFigure.Measure.Pannel,...=
    'Value','',...
    'Callback',@(h,e)disp(e),...
    'Label','Note:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
	'IsMultiLine', true,...
    'Position',[0.05 0.05 0.3 0.15]);



%% Popup for select the study
	StudyFigure.StudySelector = uiw.widget.EditablePopupWithButton(...
    'Parent',StudyFigure.MainFigure,...
    'Items',{dbNIRS.Study.Nome},...
    'Value',Hmain.Tree.Main.SelectedNodes.Name,...
    'Callback',@(h,e)disp(e.Interaction),...
    'Callback',@(h,e)disp(e),...
    'Label','Study',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Padding',2,... %Add some padding around the widget
    'Units','normalized',...
    'Position',[0.05 0.30 0.3 0.05]);

%% popup for select the probe 
	StudyFigure.ProbeSelector = uiw.widget.EditablePopupWithButton(...
    'Parent',StudyFigure.MainFigure,...
    'Items',{'USA','Canada','Mexico'},...
    'SelectedIndex',2,...
    'Value','France',...
    'Callback',@(h,e)disp(e.Interaction),...
    'Callback',@(h,e)disp(e),...
    'Label','Probe',...
    'LabelLocation','left',...
    'LabelWidth',90,...
    'Padding',2,... %Add some padding around the widget
    'Units','normalized',...
    'Position',[0.05 0.25 0.3 0.05]);

%% File selector for the measure data

	StudyFigure.MeasureSelector = uiw.widget.FileSelector(...
    'Parent', StudyFigure.MainFigure, ...
    'Value', '/home/pagno/Desktop/dati/demodata.txt', ...
    'Pattern', {'*.txt','TXT files (*.txt)'}, ...
    'Callback',@(handle, event)FastLoadDatatoNewMeasureGUI(handle, event, StudyFigure),...
	'UserData',StudyFigure,...
    'Label','Choose a data file:', ...
    'LabelLocation','left',...
    'LabelWidth',150,...
    'Units', 'normalize', ...
    'Position', [0.05 0.15 0.5 0.04]);
	
	
%% 	File selector for the video
	StudyFigure.VideoSelector= uiw.widget.FileSelector(...
    'Parent', StudyFigure.MainFigure, ...
    'Value', 'C:\matlab.mat', ...
    'Pattern', {' *.txt','TXT files (*.txt)' ; '*.mat','MATLAB MAT files (*.mat)'; '*.csv','CSV files (*.csv)'}, ...
    'Callback',@(h,e)disp(e),...
    'Label','Choose a video file:', ...
    'LabelLocation','left',...
    'LabelWidth',150,...
    'Units', 'normalize', ...
    'Position', [0.05 0.05 0.5 0.04]);


%% Button

		StudyFigure.LoadButton = uicontrol('Style', 'pushbutton',...
		'Parent', StudyFigure.MainFigure, ...
		'String', 'Load',...
		'Units', 'normalize', ...
        'Position', [0.8 0.15 0.1 0.04],...
        'Callback', {@LoadDatatoNewMeasureGUI ,StudyFigure ,Hmain}); 
	
	StudyFigure.MainFigure.Visible = 'on';

end



%% Auxiliary function
function	LoadDatatoNewMeasureGUI(~ ,~ ,StudyFigureHandle, MainHandle)

		%% store all useful figure propretybefore close it
		
		selectedMeasurePath = StudyFigureHandle.MeasureSelector.Value;   %path of the datatfile
		selectedStudyIdx = StudyFigureHandle.StudySelector.SelectedIndex;  %idx og the study associated 
		selectedStudyID = MainHandle.Tree.Main.SelectedNodes.Value;
		
		%create a subject variable
		subjectBDate = StudyFigureHandle.Subject.BirthDate.Value;
		subjectAge =  datetime - datetime(subjectBDate);
		Subject = NIRSSubject('name', StudyFigureHandle.Subject.Name.Value,...
				'sname', StudyFigureHandle.Subject.Surname.Value,...
				'bdate', StudyFigureHandle.Subject.BirthDate.Value,...
				'age', subjectAge,...
				'apgar1', StudyFigureHandle.Subject.Apgar1.Value,...
				'apgar5', StudyFigureHandle.Subject.Apgar5.Value,...
				'note', StudyFigureHandle.Subject.Note.Value);
			
		measureNote = StudyFigureHandle.Subject.Note.Value; %note on the measure
		
	    close(StudyFigureHandle.MainFigure)
		if exist(selectedMeasurePath , 'file')	
			%% add a branch to the main tree and use it for the loading bar
			
			MainHandle.Tree.StudyNode(selectedStudyIdx).NewMeasures.MainNode = uiw.widget.TreeNode(... 
				'Name','          ' ,...
				'Parent',MainHandle.Tree.StudyNode(selectedStudyIdx).MainNode...
			);
			
 				%setIcon(Hmain.Tree.StudyNode(iStudy).NewMeasures.MainNode,measureIcon);%add the measure loading icon
			
			%% creiamo e salviao il file dei dati
			DataNIRS = LoadBOXYdata(selectedMeasurePath, [], [] , MainHandle.Tree.StudyNode(selectedStudyIdx).NewMeasures.MainNode ); %load all the data present in the file
 			
			DataNIRS = NIRSMeasure(DataNIRS,...
				'StudyID',selectedStudyID,... 
				'Subject',Subject,...
				'Note',measureNote,...
				'Probe', [],...%%cercarlo nel database 
				'Eventss',[],...%%tirarli fuori in qualche modo
				'Video',[]... %%se ce lo carichi altrimenti no
				); % load all the metadata present in the window
			
			DataBase = addmeasuredatabase(DataNIRS,MainHandle.dataBasePath);
			
			MainHandle = NIRSTree(MainHandle,DataBase);
			MainHandle.Tree.Main.expandNode(MainHandle.Tree.StudyNode(selectedStudyIdx).MainNode);
		
			else
				error('file not found')
		end
		
end
		


function	FastLoadDatatoNewMeasureGUI(ObjHandle ,event ,MainHandle)

		set(ObjHandle, 'Enable', 'off')
		drawnow;
		if exist(event.NewValue , 'file')	
			DataNIRS = LoadBOXYdata( event.NewValue,[], 'f', []);
 			MainHandle.Measure.Date.Value = DataNIRS.MeasureInfo.Date;
			MainHandle.Measure.Length.Value = [num2str(DataNIRS.MeasureInfo.Duration),' s'];
			MainHandle.Measure.DetectorCH.Value = num2str(DataNIRS.MeasureInfo.AqInfo.DetectorChannel);
			MainHandle.Measure.AnalogCH.Value = num2str(DataNIRS.MeasureInfo.AqInfo.AuxiliaryAnalogChannels);
			
			else
				Error('file not found')
		end
		set(ObjHandle, 'Enable', 'on')
end


function renableHandle(~,~, objHandle)
	set(objHandle, 'Enable', 'on')
end


