function viewer(DataNIRS, theme)

Hmain = []; % handles to uicontrols and graphics
screenSize = get(0,'ScreenSize');
feature('DefaultCharacterSet', 'UTF8');

% Set main figure size
figureW = screenSize(3) * 3/4;   % Screen width in pixels
figureH = screenSize(4) * 3/4;   % Screen height in pixels
%figureRatio = figureW / figureH;

% Set UI objects size
%mainAxesWidth = .65;
%panelWidth = (1-mainAxesWidth) / 2;
stepW = 0.02;
stepH = 0.02;
panelaxesW = 1-2*stepW;
panelaxesH = 0.7;
npanels = 4;
panelW = (1-(npanels+1)*stepW)/npanels;
panelH = 1-panelaxesH-3*stepH;

% Set UI objects position
figurePosition = [screenSize(3)/2-figureW/2 screenSize(4)/2-figureH/2 figureW figureH];

% Set color theme
%theme = 'classic';
switch theme
    case 'classic'
        backgroundColor = get(0,'DefaultUicontrolBackgroundcolor');
        foregroundColor = 'k';
        highlightColor = [211 211 211]/255;
    case 'dark'
        backgroundColor = [68 68 68]/255;
        foregroundColor = 'w';
        highlightColor = [92 92 92]/255;
end

% Set font
if ismac
    defaultFontName = 'Lucida Grande';
    if sum(strcmp(listfonts,defaultFontName)) < 1
        defaultFontName = 'Helvetica';
    end
elseif ispc
    defaultFontName = 'Lucida Sans Unicode';
    if sum(strcmp(listfonts,defaultFontName)) < 1
        defaultFontName = 'Helvetica';
    end
else
    defaultFontName = 'Helvetica';
end

% UI objects
Hmain.mainFigure = figure('Position', figurePosition, ...
    'Visible', 'on', ...
    'Resize', 'on',...
    'Name', 'Viewer', ...
    'Numbertitle', 'off', ...
    'Tag', 'sensors_viewer', ...
    'Color', backgroundColor, ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL');

%Hmain.mainToolbar = uitoolbar('Parent', Hmain.mainFigure);

Hmain.menu.menuFile = uimenu('Parent', Hmain.mainFigure, 'Label', 'File');
Hmain.menu.menuFile_loadData = uimenu('Parent', Hmain.menu.menuFile, ...
    'Label', 'Load Data...', ...
    'Callback', @load_data);
Hmain.menu.menuFile_export = uimenu('Parent', Hmain.menu.menuFile, ...
    'Label', 'Export');
Hmain.menu.menuFile_export_export2png = uimenu('Parent', Hmain.menu.menuFile, ...
    'Label', 'Export to png', ...
    'Callback', @export2png);
Hmain.menu.menuFile_quit = uimenu('Parent', Hmain.menu.menuFile, ...
    'Label', 'Quit', ...
    'Callback', {@closewindow, Hmain.mainFigure});

Hmain.menu.menuEdit = uimenu('Parent', Hmain.mainFigure, 'Label', 'Edit');

Hmain.menu.menuView = uimenu('Parent', Hmain.mainFigure, 'Label', 'View');
Hmain.menu.menuView_openTable = uimenu('Parent', Hmain.menu.menuView, ...
    'Label', 'Open Table...');



%% Panels
panellabels = {'Measure', 'Subject', 'Probe', 'Channel'};

labels = {...
          {'Measure ID', 'Duration', 'Samples', 'Sampling Rate', 'Type', 'sciao'}, ...
          {'pippo', 'pluto'}, ...
          {'topolino', 'paperino', 'qui', 'quo', 'qua'}, ...
          {'archimede'}, ...
         };

	 
values = {...
          {DataNIRS.MeasureID, [num2str(DataNIRS.MeasureInfo.Duration) ' s'], num2str(height(DataNIRS.Data)), [num2str(DataNIRS.MeasureInfo.AqInfo.UpdateRate) ' Hz'], 'ciao', 'sciao'}, ...
          {'pippo', 'pluto'}, ...
          {'topolino', 'paperino', 'qui', 'quo', 'qua'}, ...
          {'archimede'}, ...
         }; 
	 
	 
npanels = length(panellabels);
panelwidth = (1-(npanels+1)*stepW)/npanels;

for jj = 1:1:npanels
    
    panel_position = [jj*stepW+(jj-1)*panelwidth stepH panelwidth panelH];
    Hmain.metadata(jj).panel = uipanel('parent', Hmain.mainFigure,...
        'Position', panel_position, ...
        'Units', 'normalized', ...
        'BackgroundColor', backgroundColor, ...
        'ForegroundColor', foregroundColor, ...
        'HighlightColor', highlightColor, ...
        'ShadowColor', [211 211 211]/255, ...
        'BorderType', 'line', ...
        'FontWeight', 'bold', ...
        'FontSize', 8, ...
        'FontName', defaultFontName, ...
        'Visible', 'on', ...
        'Title', panellabels{jj});
    
    currentlabels = fliplr(labels{1,jj});
	currentvalues = fliplr(values{1,jj});
	
    nlines = length(currentlabels);
    boxheight = 1/(nlines+2);
    for ii = 1:1:nlines
        Hmain.metadata(jj).label(ii) = uicontrol('Parent', Hmain.metadata(jj).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.1 ii*boxheight 0.3 0.1], ...
            'FontWeight', 'bold', ...
            'FontSize', 8, ...
            'FontAngle', 'italic', ...
            'HorizontalAlignment', 'left', ...
            'String', currentlabels{ii});
        Hmain.metadata(jj).value(ii) = uicontrol('Parent', Hmain.metadata(jj).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.4 ii*boxheight 0.6 0.1], ...
            'FontWeight', 'bold', ...
            'FontAngle', 'italic', ...
            'FontSize', 8, ...
            'String', currentvalues{ii});
    end
end

%% Panel axes
panelaxes_position = [stepW panelH+2*stepH panelaxesW panelaxesH];
Hmain.plot.panel = uipanel('parent', Hmain.mainFigure,...
    'Position', panelaxes_position, ...
    'Units', 'normalized', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'HighlightColor', highlightColor, ...
    'ShadowColor', [211 211 211]/255, ...
    'BorderType', 'line', ...
    'FontWeight', 'bold', ...
    'FontSize', 6, ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Time series');

Hmain.plot.bigaxes1 = axes('parent', Hmain.plot.panel,...
    'Position', [0.05 0.2 0.9 0.7], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

Hmain.plot.bigaxes2 = axes('parent', Hmain.plot.panel,...
    'Position', [0.05 0.2 0.9 0.7], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

Hmain.plot.smallaxes = axes('parent', Hmain.plot.panel,...
    'Units', 'normalized', ...
    'Position', [0.1 0.04 0.8 0.07], ...
    'Color', backgroundColor, ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...   
    'Visible', 'off', ...
    'Box', 'on', ...
    'XLimMode', 'auto', ...
    'YLimMode', 'auto', ...
    'XGrid', 'off', ...
    'YGrid', 'off');

Hmain.plot.editmin = uicontrol('Parent', Hmain.plot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.06 0.04 0.05], ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@set_time_window_min, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate}, ...
    'String', 'min');

Hmain.plot.editmax = uicontrol('Parent', Hmain.plot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.06 0.04 0.05], ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@set_time_window_max, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate}, ...
    'String', 'max');

Hmain.plot.buttonBw10 = uicontrol('Parent', Hmain.plot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.03 0.02 0.03], ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate}, ...
    'String', '<<');
Hmain.plot.buttonBw1 = uicontrol('Parent', Hmain.plot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.03 0.02 0.03], ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate}, ...
    'String', '<');
Hmain.plot.buttonFw10 = uicontrol('Parent', Hmain.plot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.93 0.03 0.02 0.03], ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate}, ...
    'String', '>>');
Hmain.plot.buttonFw1 = uicontrol('Parent', Hmain.plot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.03 0.02 0.03], ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate}, ...
    'String', '>');


%% Main plot
nirsdata = table2array(DataNIRS.Data(:,6:197));
channelColors = lines(size(nirsdata, 2));
aa = 1;
axes(Hmain.plot.bigaxes1)
axis tight
cla;
hold on
for ii = 1:1:size(nirsdata,2)
    Hmain.plot.lines1(ii) = plot(DataNIRS.Data.reltime, nirsdata(:,ii), 'LineWidth', 1, 'LineStyle', '-');
    set(Hmain.plot.lines1(ii), 'Color', channelColors(ii,:));
    aa = aa+1;
end
Hmain.plot.lines1_selection = findall(Hmain.plot.lines1, 'Type', 'Line');
set(Hmain.plot.lines1_selection, 'buttonDownFcn', {@change_line_width, channelColors, get(Hmain.plot.lines1_selection(1), 'LineWidth'), 2})
Hmain.plot.bigaxes1.XLabel.String = 'Time (s)';
Hmain.plot.bigaxes1.YLabel.String = 'Intensity (a.u.)';
x2 = 1:1:size(nirsdata,1);
%y2 = 1:1:size(nirsdata,1);
y2 = DataNIRS.Data.reltime/DataNIRS.MeasureInfo.AqInfo.UpdateRate;
line(x2, y2, 'Parent', Hmain.plot.bigaxes2, 'Color', 'none')
%linkaxes([Hmain.plot.bigaxes1, Hmain.plot.bigaxes2], 'x')
Hmain.plot.bigaxes2.XLabel.String = 'Time (samples)';
Hmain.plot.bigaxes2.YTickLabel = [];

%% Overall plot
axes(Hmain.plot.smallaxes)
axis tight
cla;
hold on
for ii = 1:1:size(nirsdata,2)
    Hmain.plot.lines2(ii) = plot(DataNIRS.Data.reltime, nirsdata(:,ii), 'LineWidth', 1, 'LineStyle', '-');
    set(Hmain.plot.lines2(ii), 'Color', channelColors(ii,:));
    aa = aa+1;
end
Hmain.plot.editmin.String = num2str(DataNIRS.Data.reltime(1));
Hmain.plot.editmax.String = num2str(DataNIRS.Data.reltime(end));
Hmain.plot.rectangle = rectangle('Position', [str2double(Hmain.plot.editmin.String) min(nirsdata(:)) str2double(Hmain.plot.editmax.String)-str2double(Hmain.plot.editmin.String) max(nirsdata(:))-min(nirsdata(:))], 'Curvature', [0 0], 'EdgeColor', foregroundColor);
Hmain.plot.lines2_selection = findall(Hmain.plot.lines2, 'Type', 'Line');
set(Hmain.plot.lines2_selection, 'buttonDownFcn', {@move_rectangle, Hmain.plot, DataNIRS.MeasureInfo.AqInfo.UpdateRate});

%% Populate metadata

%% Turn figure on
Hmain.mainFigure.Visible = 'on';
